version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=aws_project01
      - MYSQL_ROOT_PASSWORD=admin12345
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-db:
    driver: local