version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=aws_project01
      - MYSQL_ROOT_PASSWORD=admin12345
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sns:4566,sqs:4567
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
volumes:
  mysql-db:
    driver: local

