server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /application
spring:
  # SETUP DATABASE
  datasource:
    url: jdbc:mariadb://localhost:3306/aws_project01?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin12345
  # SETUP JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # SETUP FLYWAY (MIGRATIONS)
  flyway:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:aws_project01}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin12345}
    schemas:
      - ${DATABASE:aws_project01}
    baseline_on_migrate: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher


